feat: add time to read on blog post
LoginRadius/engineering-portal pull request #238
Opened 2020-09-25 18:24 UTC by Kalovelo

##### Description of change

This PR  solves #230 .

The human reading is speed is around 220 words per minute.
Therefore, this PR implements a functionality of stripping the blog post details from HTML & style tags, and checking the total words of it divided by the human read words per minute.

2020-09-28 07:15 UTC, mohammed786 requested changes
Hi @Kalovelo , thanks for contributing in Loginradius Engineering Blog.

The change looks good on the **post page**, but as you are calculating the time in the **post.js**, the reading time is not showing in the homepage list. 

Can you please update your PR and try to show it in the home page **post list**?

Feel free to ask questions if you have.

2020-10-01 07:30 UTC, Kalovelo commented
Hello @mohammed786 could you please review the update? Thanks!

2020-10-05 10:26 UTC, mohammed786 approved these changes
Looks Good @Kalovelo 

Thanks for contributing.

2020-10-05 10:52 UTC, puneetsingh24 approved these changes

2020-10-05 10:52 UTC, merged