Technical Blog "Build a Twitter Bot Using NodeJS"
LoginRadius/engineering-portal pull request #338
Opened 2020-10-02 05:44 UTC by Ninjavin

#### Checklist

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change

##### Author Details for Blog Post Entry

id: Vineeta Jain
bio: Third-year undergraduate and a Full Stack Web Developer. A team-player with a can-do attitude.
github: [Ninjavin](https://github.com/Ninjavin)
twitter: [vineeta_vj](https://twitter.com/vineeta_vj)
medium: [vinjain2006](https://medium.com/@vinjain2006)

2020-10-07 14:08 UTC, puneetsingh24 reviewed
@Ninjavin As per our contribution guidelines, can you please resize the cover image to 1200px to 800px

2020-10-07 20:01 UTC, Ninjavin commented
@puneetsingh24 I have resized the image. Thank you.

2020-10-09 08:56 UTC, puneetsingh24 requested changes
Hello @Ninjavin 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, we recommend uploading the source code used in the blog post to the repo - https://github.com/LoginRadius/engineering-blog-samples and give the link to the folder in the blog.

Can you please create a separate pull request on blog samples repo?

Thanks

2020-10-09 10:06 UTC, Ninjavin commented
@puneetsingh24 I have created a separate PR on Engineering Blog Samples repo PR [#82](https://github.com/LoginRadius/engineering-blog-samples/pull/82).
Thank you.

2020-10-14 08:57 UTC, vyasriday commented on content/blog/build-a-twitter-bot-using-nodejs/index.md
> +axios("https://official-joke-api.appspot.com/random_joke").then(Response => {
@Ninjavin Does axios support api request like this? Shouldn't this be either a `.get` or a config object`?

2020-10-14 09:10 UTC, vyasriday approved these changes

2020-10-14 09:23 UTC, puneetsingh24 approved these changes

2020-10-14 09:26 UTC, merged