React Context API blog post
LoginRadius/engineering-portal pull request #365
Opened 2020-10-04 23:09 UTC by eylonronen

#### Checklist

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [ ] You created a branch from `dev` branch.
- [ ] You PR is raised on `dev` branch and not on`master`.
- [ ] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [ ] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [ ] Checked for any duplicate blog entry.
- [ ] Checked for all grammatical errors in the blog.
- [ ] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [ ] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change

##### Author Details for Blog Post Entry

2020-10-06 10:39 UTC, vyasriday requested changes

2020-10-06 10:39 UTC, vyasriday commented on content/blog/react-contedxt-api/index.md
> +## What is Context API?
The sentence should be ended with a full stop, right?

2020-10-06 10:39 UTC, vyasriday commented on content/blog/react-contedxt-api/index.md
> +**Provider** is a component that as it names suggests provides the state to its children.
should be `as it's name suggests`

2020-10-06 10:39 UTC, vyasriday commented on content/blog/react-contedxt-api/index.md
> +Redux is great and came perfectly to answer the need for state management. actually it answered this need so well that it came to be known that you can't be a "true" React developer if you don't know
start sentence with a capital.  `Actually it answered this need . . . `

2020-10-06 10:39 UTC, vyasriday commented on content/blog/react-contedxt-api/index.md
> +  2. One of the great advantages of React's one-way data binding is that it's easy to understand - A component passes state to its children. Using Redux takes it away from us
End sentence with a full stop

2020-10-06 10:39 UTC, vyasriday commented on content/blog/react-contedxt-api/index.md
> +First, make sure you need it. sometimes people use shared state across nested components instead of just passing it as props.
A sentence must start with a capital : `Sometimes people use . . . `

2020-10-06 11:14 UTC, puneetsingh24 requested changes
Hello @eylonronen, Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, a blog should contain minimum of 600 words excluding meta description on top.

Please add more information about react context API

2020-10-07 07:50 UTC, vyasriday approved these changes

2020-10-07 08:05 UTC, puneetsingh24 approved these changes

2020-10-07 12:32 UTC, merged

2020-10-07 12:41 UTC, vyasriday commented
@eylonronen Hey can you provide us with some details like your name, Linkedin and all to show it on your profile for our engineering blog?

2020-10-07 13:09 UTC, eylonronen commented
name: Eylon Ronen
linkedin: https://www.linkedin.com/in/eylon-ronen-366916157