Add blogpost about Apache Beam
LoginRadius/engineering-portal pull request #389
Opened 2020-10-08 14:15 UTC by Better-Boy

title: apache-beam-blog
description: Apache Beam for Dummies Blog

#### Checklist

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change
Added a new blogpost - **Apache Beam for Dummies**

##### Author Details for Blog Post Entry

id: Abhilash K R
stackoverflow: https://stackoverflow.com/users/6849682/bigbounty

2020-10-09 13:20 UTC, puneetsingh24 requested changes
Hello @Better-Boy 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, we recommend using the cover image of ratio 3:2 and size 1200px X 800px. 

Please upload a new cover image with appropriate size

Thanks

2020-10-10 04:17 UTC, Better-Boy commented
Hi @puneetsingh24 Uploaded 1200x800 resolution new image. Please check

2020-10-16 07:19 UTC, puneetsingh24 approved these changes

2020-10-16 08:40 UTC, vyasriday approved these changes

2020-10-16 08:40 UTC, merged