Add blog on advanced vim
LoginRadius/engineering-portal pull request #554
Opened 2021-01-03 09:48 UTC by iamshubhankarkhare

#### Checklist

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change
Added a new blog on Vim

##### Author Details for Blog Post Entry
  id: Shubhankar Khare
  bio: A diligent and prompt learner, Shubhankar Khare is a passionate full stack web developer from India. He is crazy about 
  learning new technologies and is an open source enthusiast.
  github: "iamshubhankarkhare"
  linkedin: "shubhankar-khare"

2021-01-03 09:51 UTC, iamshubhankarkhare commented
@vyasriday @puneetsingh24 please review..

2021-08-31 09:39 UTC, Akash-Patil requested changes
Hi @iamshubhankarkhare,

I have reviewed the document and suggested a few minor changes. Please have a look. 

Regards,
@Akash-Patil

2021-08-31 09:39 UTC, Akash-Patil commented on content/vim-level-up/index.md
> +nnoremap <C-t> :tabnew<Cr>
Change `<Cr>` to `<CR>` for "carriage return" as done in other cases.

2021-08-31 09:39 UTC, Akash-Patil commented on content/vim-level-up/index.md
> +In simple terms, a _buffer_ is a file that has been loaded into memory. Everything you do in VIM is in a buffer. You can list all the buffers by `:Buffers`. And then, if you want to check out a parti
Should be `:buffers` instead of `:Buffers`. Please confirm this.

2021-09-22 05:41 UTC, mohammed786 approved these changes

2021-09-22 05:42 UTC, merged