Added blog on eva service
LoginRadius/engineering-portal pull request #598
Opened 2021-02-18 13:17 UTC by pareek-narendra

#### Checklist

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [ ] You created a branch from `dev` branch.
- [ ] You PR is raised on `dev` branch and not on`master`.
- [ ] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [ ] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [ ] Checked for any duplicate blog entry.
- [ ] Checked for all grammatical errors in the blog.
- [ ] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [ ] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change

##### Author Details for Blog Post Entry

2021-02-18 13:21 UTC, puneetsingh24 approved these changes

2021-02-19 05:49 UTC, vyasriday requested changes

2021-02-19 05:49 UTC, vyasriday commented on content/eva-google-script/index.md
> +title: "Verify Emails in Google Sheet in bulk"
Can be `Bulk Email Verification in Google Sheets`.

2021-02-19 05:49 UTC, vyasriday commented on content/eva-google-script/index.md
> +description: "Learn how to validate email addresses using eva services in google sheet."
Make it `Google Sheets` not Google Sheet.

2021-02-19 06:16 UTC, vyasriday approved these changes

2021-02-19 11:37 UTC, merged