added blog on registration and authentication in django using loginra…
LoginRadius/engineering-portal pull request #713
Opened 2021-07-21 15:08 UTC by Tammibriggs

…dius

#### Checklist

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change

##### Author Details for Blog Post Entry

id: Taminoturoko Briggs
bio: An enthusiastic software developer conversant with Python and JavaScript. 
github: https://github.com/Tammibriggs
stackoverflow: https://stackoverflow.com/users/15485047/tammibriggs?tab=topactivity
linkedin: https://www.linkedin.com/in/taminoturoko-briggs-b98251203/

2021-07-22 10:14 UTC, abhir9 approved these changes
Looks good from technical side

2021-07-23 07:21 UTC, raghunath-r-a requested changes
Hi @Tammibriggs 

We have made suggestions to improve the article. Please review them and make the necessary changes. 

Thank you,
@raghunath-r-a

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +all this views does is to render a html page as a response.
```suggestion
All this view does is render an HTML page as a response.
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +Now we need to add the URL pattern for this views.
```suggestion
Now, we need to add the URL pattern for this view.
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +The `register_n_login` views can now be accessed by a URL. It's time to create a template for our views. But before we do that, let me introduce some basic styling we will use in our application.
```suggestion
The `register_n_login` view can now be accessed by a URL. It's time to create a template for our views. But before we do that, let me introduce some basic styling we will use in our application.
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +Now lets create the template for our `register_n_login` views
```suggestion
Now, let's create the template for our `register_n_login` views
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +We used an `onclick` event on both the register and login button, which when clicked changes the windows location to the [Auth Page (IDX)](https://www.loginradius.com/docs/developer/concepts/idx) reg
```suggestion
We used an `onclick` event on both the register and login buttons, which when clicked changes the window's location to the [Auth Page (IDX)](https://www.loginradius.com/docs/developer/concepts/idx) register and login page respectively.
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +>
```suggestion
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +Also, in the register and login link, we replaced the {RETURN_URL} parameter with http://127.0.0.1:8000/profile/, which is the users profile page we are going to create shortly.
```suggestion
Also, in the register and login link, we replaced the {RETURN_URL} parameter with http://127.0.0.1:8000/profile/, which is the user profile page we are going to create shortly.
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +Now when you click the register or login button your will see a page like this:
```suggestion
Now, when you click the register or login button, you will see a page like this:
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +we are going to retrieve the user's data from the access token.
```suggestion
We are going to retrieve the user's data from the access token.
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +Now lets create the view that will be responsible for retrieving user data
```suggestion
Now, let's create the view that will be responsible for retrieving user data.
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +- We created a `try` and `except` block. In the `try` block we used the `authentication.get_profile_by_access_token` method to retrieve the user data from the access token and assigned it to a variab
```suggestion
- We first checked if there is a token parameter attached to the request.
- If true, we created a `try` and `except` block. In the `try` block, we used the `authentication.get_profile_by_access_token` method to retrieve the user data from the access token and assigned it to a variable called `user_data`; while in the `except` block, we returned a HttpResponse of the error that occurred if the `try` block fails.
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +- If the `try` block successfully retrieved the user's data, we rendered a *profile.html* page, and also attached the `user_data` variable to the response.
```suggestion
- If the `try` block successfully retrieved the user's data, we rendered a *profile.html* page and also attached the `user_data` variable to the response.
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +Here we displayed the Provider, Email and NoOfLogins from the `user_data`. These are just some of the data present in the `user_data`.
```suggestion
Here, we displayed the Provider, Email, and NoOfLogins from the `user_data`. These are just some of the data points present in the `user_data`.
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +Now if you run your development server then register and login a user  you should see a page like this:
```suggestion
Now, if you run your development server, and then register and login a user, you should see a page like this:
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +In this tutorial we have looked at how we can use LoginRadius for registration and authentication in Django. We started by giving a brief introduction to LoginRadius, what it is, its benefits, and ho
```suggestion
In this tutorial, we discussed how to use LoginRadius for registration and authentication in Django. We started by introducing LoginRadius, what it is, its benefits, and how to get started with it. Then, we illustrated building a demo application with Django and implemented registration and authentication using LoginRadius.
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +## Github repo
```suggestion
**GitHub repo:** https://github.com/Tammibriggs/radiusAuth
```

2021-07-23 07:21 UTC, raghunath-r-a commented on content/registration-and-authentication-in-django-using-loginRadius/index.md
> +https://github.com/Tammibriggs/radiusAuth
```suggestion
```

2021-07-26 15:10 UTC, Tammibriggs commented
Hi,

I have made the suggested changes.

Regards,
Taminoturoko Briggs.

On Fri, Jul 23, 2021, 8:22 AM Raghunath Reddy ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Tammibriggs <https://github.com/Tammibriggs>
>
> We have made suggestions to improve the article. Please review them and
> make the necessary changes.
>
> Thank you,
> @raghunath-r-a <https://github.com/raghunath-r-a>
> ------------------------------
>
> In
> content/registration-and-authentication-in-django-using-loginRadius/index.md
> <https://github.com/LoginRadius/engineering-portal/pull/713#discussion_r675322807>
> :
>
> > @@ -0,0 +1,522 @@
>
> +---
>
> +title: "Registration and Authentication in Django using LoginRadius"
>
> +date: "2021-7-21"
>
> +coverImage: "coverImage.png"
>
> +author: "Taminoturoko Briggs"
>
> +tags: "Django, auth"
>
>
> ⬇️ Suggested change
>
> -tags: "Django, auth"
>
> +tags: "Django, Authentication, User Registration"
>
>
> ------------------------------
>
> In
> content/registration-and-authentication-in-django-using-loginRadius/index.md
> <https://github.com/LoginRadius/engineering-portal/pull/713#discussion_r675323476>
> :
>
> > @@ -0,0 +1,522 @@
>
> +---
>
> +title: "Registration and Authentication in Django using LoginRadius"
>
> +date: "2021-7-21"
>
> +coverImage: "coverImage.png"
>
> +author: "Taminoturoko Briggs"
>
> +tags: "Django, auth"
>
> +description: "In this tutorial you will learn how to implement user registration and authentication in Django using loginRadius"
>
>
> ⬇️ Suggested change
>
> -description: "In this tutorial you will learn how to implement user registration and authentication in Django using loginRadius"
>
> +description: "In this tutorial, you will learn how to implement user registration and authentication in Django using LoginRadius"
>
>
> ------------------------------
>
> In
> content/registration-and-authentication-in-django-using-loginRadius/index.md
> <https://github.com/LoginRadius/engineering-portal/pull/713#discussion_r675323755>
> :
>
> > +# Registration and Authentication in Django using LoginRadius
>
> +*In this tutorial you will learn how to implement user registration and authentication in Django using loginRadius*
>
>
> ⬇️ Suggested change
>
> -# Registration and Authentication in Django using LoginRadius
>
> -*In this tutorial you will learn how to implement user registration and authentication in Django using loginRadius*
>
>
> ------------------------------
>
> In
> content/registration-and-authentication-in-django-using-loginRadius/index.md
> <https://github.com/LoginRadius/engineering-portal/pull/713#discussion_r675324359>
> :
>
> > @@ -0,0 +1,522 @@
>
> +---
>
> +title: "Registration and Authentication in Django using LoginRadius"
>
> +date: "2021-7-21"
>
> +coverImage: "coverImage.png"
>
> +author: "Taminoturoko Briggs"
>
> +tags: "Django, auth"
>
> +description: "In this tutorial you will learn how to implement user registration and authentication in Django using loginRadius"
>
> +---
>
> +
>
> +# Registration and Authentication in Django using LoginRadius
>
> +*In this tutorial you will learn how to implement user registration and authentication in Django using loginRadius*
>
> +
>
> +## Prerequisite
>
> +
>
> +To follow up on this tutorial, you should be familiar with Python and Django a python framework.
>
>
> ⬇️ Suggested change
>
> -To follow up on this tutorial, you should be familiar with Python and Django a python framework.
>
> +You should be familiar with Python and Django, a Python framework.
>
>
> ------------------------------
>
> In
> content/registration-and-authentication-in-django-using-loginRadius/index.md
> <https://github.com/LoginRadius/engineering-portal/pull/713#discussion_r675325204>
> :
>
> > +coverImage: "coverImage.png"
>
> +author: "Taminoturoko Briggs"
>
> +tags: "Django, auth"
>
> +description: "In this tutorial you will learn how to implement user registration and authentication in Django using loginRadius"
>
> +---
>
> +
>
> +# Registration and Authentication in Django using LoginRadius
>
> +*In this tutorial you will learn how to implement user registration and authentication in Django using loginRadius*
>
> +
>
> +## Prerequisite
>
> +
>
> +To follow up on this tutorial, you should be familiar with Python and Django a python framework.
>
> +
>
> +## Overview
>
> +
>
> +We will start by giving a brief introduction to LoginRadius, what it is and some benefits of using LoginRadius, then will move over to see how we can implement user Registration and authentication in Django using LoginRadius
>
>
> ⬇️ Suggested change
>
> -We will start by giving a brief introduction to LoginRadius, what it is and some benefits of using LoginRadius, then will move over to see how we can implement user Registration and authentication in Django using LoginRadius
>
> +First, we briefly introduce LoginRadius, what it is. and some benefits of using it; then, will move over to see how to implement user registration and authentication in Django using LoginRadius.
>
>
> ------------------------------
>
> In
> content/registration-and-authentication-in-django-using-loginRadius/index.md
> <https://github.com/LoginRadius/engineering-portal/pull/713#discussion_r675325405>
> :
>
> > +---
>
> +
>
> +# Registration and Authentication in Django using LoginRadius
>
> +*In this tutorial you will learn how to implement user registration and authentication in Django using loginRadius*
>
> +
>
> +## Prerequisite
>
> +
>
> +To follow up on this tutorial, you should be familiar with Python and Django a python framework.
>
> +
>
> +## Overview
>
> +
>
> +We will start by giving a brief introduction to LoginRadius, what it is and some benefits of using LoginRadius, then will move over to see how we can implement user Registration and authentication in Django using LoginRadius
>
> +
>
> +## Introduction
>
> +
>
> +**What is LoginRadius**
>
>
> ⬇️ Suggested change
>
> -**What is LoginRadius**
>
> +**What is LoginRadius?**
>
>
> ------------------------------
>
> In
> content/registration-and-authentication-in-django-using-loginRadius/index.md
> <https://github.com/LoginRadius/engineering-portal/pull/713#discussion_r675327764>
> :
>
> > +*In this tutorial you will learn how to implement user registration and authentication in Django using loginRadius*
>
> +
>
> +## Prerequisite
>
> +
>
> +To follow up on this tutorial, you should be familiar with Python and Django a python framework.
>
> +
>
> +## Overview
>
> +
>
> +We will start by giving a brief introduction to LoginRadius, what it is and some benefits of using LoginRadius, then will move over to see how we can implement user Registration and authentication in Django using LoginRadius
>
> +
>
> +## Introduction
>
> +
>
> +**What is LoginRadius**
>
> +
>
> +
>
> +> LoginRadius is SaaS based CIAM platform that manages consumer identity and privacy, allowing businesses to customize a secure digital experience their consumers will love.
>
>
> ⬇️ Suggested change
>
> -> LoginRadius is SaaS based CIAM platform that manages consumer identity and privacy, allowing businesses to customize a secure digital experience their consumers will love.
>
> +LoginRadius is a SaaS-based CIAM platform. It offers simplified, robust features to manage customer identity, privacy, and access -- allowing developers and businesses to provide a seamless and secure digital experience for their customers.
>
>
> ------------------------------
>
> In
> content/registration-and-authentication-in-django-using-loginRadius/index.md
> <https://github.com/LoginRadius/engineering-portal/pull/713#discussion_r675328359>
> :
>
> > +## Prerequisite
>
> +
>
> +To follow up on this tutorial, you should be familiar with Python and Django a python framework.
>
> +
>
> +## Overview
>
> +
>
> +We will start by giving a brief introduction to LoginRadius, what it is and some benefits of using LoginRadius, then will move over to see how we can implement user Registration and aut [...]

2021-07-27 05:37 UTC, raghunath-r-a approved these changes
Thank you, @Tammibriggs

2021-07-28 07:24 UTC, abhir9 approved these changes

2021-07-28 08:53 UTC, merged