added blog "Configure Mailazy as External SMTP Email Provider"
LoginRadius/engineering-portal pull request #725
Opened 2021-08-05 13:35 UTC by kunal-saini

#### Checklist

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change

title: add blog "Configure Mailazy as External SMTP Email Provider"

description: blog explains steps and configurations to set in order to configure LoginRadius to send emails with Mailazy

##### Author Details for Blog Post Entry

id: Kunal
bio: Kunal is a Lead Software Development Engineer at Mailazy. He graduated in Computer Science and considers himself a learner of life. He loves to play cricket, football, and computer games.
github: https://github.com/kunal-saini

2021-08-25 13:40 UTC, kunal-saini commented
Hey @raghunath-r-a @pareek-narendra @puneetsingh24 
Just wanted to check on the review, Is there something that needs to be changed. let me know. 

Thanks!

2021-09-08 07:39 UTC, Akash-Patil requested changes
Hi @kunal-saini ,

I have reviewed the document and suggested a few changes. Please have a look.

Regards,
@Akash-Patil

2021-09-08 07:39 UTC, Akash-Patil commented on content/guest-post/configure-mailazy-as-external-smtp-email-provider/index.md
> +**Step 4:** Expand "Email/SMS Provider Settings"
The steps under `Step 4: Expand "Email/SMS Provider Settings"` have to be updated to match the current flow of adding a SMTP provider in LoginRadius Developer account. Kindly update this.

2021-09-08 07:39 UTC, Akash-Patil commented on content/guest-post/configure-mailazy-as-external-smtp-email-provider/index.md
> +![lr-smtp](lr-smtp.png)
This screenshot seems to be outdated. Please add a screenshot with updated UI.

2021-09-08 09:20 UTC, kunal-saini commented
hey @raghunath-r-a @Akash-Patil since the LoginRadius developer plan no longer has the capability to configure SMTP, I would re-write the article for the enterprise plan/use-case. I have converted the PR to draft once done I will mark it ready for review again. 
thanks! 
cc; @kartiknc

2021-09-08 09:53 UTC, Akash-Patil commented
> hey @raghunath-r-a @Akash-Patil since the LoginRadius developer plan no longer has the capability to configure SMTP, I would re-write the article for the enterprise plan/use-case. I have converted the PR to draft once done I will mark it ready for review again.
> thanks!
> cc; @kartiknc

Sure, No problem. 
Thanks.

2022-05-23 10:27 UTC, raghunath-r-a commented
Closing this PR for now. Please create a new PR with updates as per new guidelines if needed. Thank you.

2022-05-23 10:27 UTC, closed without merging