How to authenticate users in nestjs
LoginRadius/engineering-portal pull request #976
Opened 2022-02-11 02:36 UTC by gathoni-k

#### Checklist

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [ x ] You created a branch from `dev` branch.
- [ x ] You PR is raised on `dev` branch and not on`master`.
- [ x ] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [ x ] You have read the [Contribution Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [ x ] Checked for any duplicate blog entry.
- [ x ] Checked for all grammatical errors in the blog.
- [ x ] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x ] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change
A tutorial on how to authenticate users using the Authentication API provided by LoginRadius in NestJS.

2022-02-15 11:11 UTC, raghunath-r-a commented
Hi @gathoni-k We're moving your PR to Phase - II.

For facilitating easier reference for readers, please add the sample/example code used in the following repo by creating a separate pull request: https://github.com/LoginRadius/engineering-blog-samples

2022-02-15 11:23 UTC, gathoni-k commented
Hey!

Okay, I will.

On Tue, 15 Feb 2022, 14:11 Raghunath Reddy, ***@***.***>
wrote:

> Hi @gathoni-k <https://github.com/gathoni-k> We're moving your PR to
> Phase - II.
>
> For facilitating easier reference for readers, please add the
> sample/example code used in the following repo by creating a separate pull
> request: https://github.com/LoginRadius/engineering-blog-samples
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LoginRadius/engineering-portal/pull/976#issuecomment-1040145533>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMMBYTX4PCTC5FCHEHZU7CLU3IYFPANCNFSM5OCZ5ZHQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-23 12:42 UTC, Akash-Patil requested changes
Hi @gathoni-k. Please note the following points: 

1. I have reviewed the blog and suggested a few changes. Kindly have a look. 
2. While testing the code, the `lrv2` variable is fetching/assigned an undefined value and hence the desired result is not returned on hitting the different routes. As suggested by @raghunath-r-a, please send a PR to https://github.com/LoginRadius/engineering-blog-samples with the demo code so that we can check for possible errors in code or if there is any other external issue from our end. After that, you can add a link to the demo in the blog.
3. Lastly, kindly rebase your branch to the latest commit of dev branch once the changes are made.

Regards,
@Akash-Patil

2022-02-23 12:42 UTC, Akash-Patil commented on content/guest-post/nestjs-authentication-with-loginradius-api/index.md
> +API_SECRET=,your api secret>
Kindly change the `,` to `<` for API_SECRET.

2022-02-23 12:42 UTC, Akash-Patil commented on content/guest-post/nestjs-authentication-with-loginradius-api/index.md
> +  email: string,
Remove the `,` here.

2022-02-23 12:42 UTC, Akash-Patil commented on content/guest-post/nestjs-authentication-with-loginradius-api/index.md
> +
Before importing, add a line stating the command used to install `loginradius-sdk`, i.e `npm i loginradius-sdk`

2022-02-23 12:42 UTC, Akash-Patil commented on content/guest-post/nestjs-authentication-with-loginradius-api/index.md
> +In `auth.guard.js`, add the following code.
Change `auth.guard.js` to `auth.guard.ts`

2022-02-23 12:42 UTC, Akash-Patil commented on content/guest-post/nestjs-authentication-with-loginradius-api/index.md
> +            request['isAuthorized'] = "Authorrized"
Spelling of `Authorized` is wrong.

2022-02-23 12:42 UTC, Akash-Patil commented on content/guest-post/nestjs-authentication-with-loginradius-api/index.md
> +To execute the signup method in the signup route, inject it in the `auth.contoller.ts` file.
`controller` is missplet in file name.

2022-02-23 12:42 UTC, Akash-Patil commented on content/guest-post/nestjs-authentication-with-loginradius-api/index.md
> +
In the Login Section, you can mention the code that needs to be injected in the `auth.controller.ts` file for the login method to work on login route, similar to as mentioned in the signup section.

2022-03-22 12:29 UTC, Akash-Patil requested changes
Hi @gathoni-k, 

Changes look good. We have reviewed you demo code PR  and merged it. Now you update the blog links in the main blog and rebase your branch with dev branch so that we can merge the blog.

Regards 
@Akash-Patil

2022-03-22 12:58 UTC, Akash-Patil approved these changes

2022-03-22 13:01 UTC, merged