Blog how to authenticate svelte apps
LoginRadius/engineering-portal pull request #981
Opened 2022-02-15 03:50 UTC by FuzzySid

#### Checklist

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change

2022-02-17 10:47 UTC, raghunath-r-a commented
Hi @FuzzySid We're moving the PR to Phase - II.

Please add sample code in the following repo by creating a separate pull request: https://github.com/LoginRadius/engineering-blog-samples

Accordingly, we can update GitHub links in lines 87 and 123

2022-02-17 16:13 UTC, FuzzySid commented
Hi @raghunath-r-a  Thanks for letting me know, I have done the needful. [Here's](https://github.com/LoginRadius/engineering-blog-samples/pull/157) the pull request for the code sample.

2022-03-03 09:09 UTC, Akash-Patil requested changes
Hi @FuzzySid,

I have reviewed the blog and suggested a couple of changes. Please have a look.
Overall, the blog is well-written and informative. 
However, there is a small issue with the demo code as mentioned below.

Right now the submodule for the svelte app is not viewable on the Github UI. In this case, it would be better to use a normal folder for the code to maintain uniformity in the blog-samples repo. Kindly resend a PR with the code in a similar way as to the other demo code examples in the repo. 

Regards,
@Akash-Patil

2022-03-03 17:09 UTC, FuzzySid commented on content/guest-post/authenticating-svelte-apps/index.md
> +Let's render the Login component inside your `App.svelte` file:
Hi @Akash-Patil 
Thanks for letting me know. I have created a new PR for the code sample [here](https://github.com/LoginRadius/engineering-blog-samples/pull/164). I believe that should do the job. Let me know once the PR is merged so I can also update the blog accordingly.

2022-03-09 04:23 UTC, raghunath-r-a commented on content/guest-post/authenticating-svelte-apps/index.md
> +Let's render the Login component inside your `App.svelte` file:
Hi @FuzzySid The code sample PR has been merged

2022-03-10 03:34 UTC, FuzzySid commented on content/guest-post/authenticating-svelte-apps/index.md
> +Let's render the Login component inside your `App.svelte` file:
I have updated the links in the blog. 
@raghunath-r-a @Akash-Patil

2022-03-10 10:01 UTC, Akash-Patil approved these changes

2022-03-10 10:19 UTC, merged